### PR TITLE
ENH: add command to display container registry

### PR DESCRIPTION
**Pull request by untzag**
## Description

Adding new command to CLI.

```
$ happi container-registry
+------------------------------------+------------------------------------+-------------------------------+
| Container Name                     | Container Class                    | Object Class                  |
+------------------------------------+------------------------------------+-------------------------------+
| Device                             | happi.device.Device                | None                          |
| OphydItem                          | happi.item.OphydItem               | None                          |
| HappiItem                          | happi.item.HappiItem               | None                          |
| bluesky_autonomic._happi.DelayItem | bluesky_autonomic._happi.DelayItem | bluesky_autonomic.DelayDevice |
| bluesky_autonomic._happi.OPAItem   | bluesky_autonomic._happi.OPAItem   | bluesky_autonomic.OPADevice   |
| yaq._happi.YAQItem                 | yaqc_bluesky._happi.YAQItem        | yaqc_bluesky.Device           |
+------------------------------------+------------------------------------+-------------------------------+
```

## Motivation and Context

For debugging purposes it's become useful for me to inspect what container types happi has successfully loaded through the entry-points system. This can be done from within Python, but now in the fast-paced world of docker and many device-providing packages it's even better to be able to see this information from the shell. Just scratching my own itch here!

## How Has This Been Tested?

Works on my machine :laughing: 

## Where Has This Been Documented?

CLI is automatically documented.

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Nice!

**Comment by klauer** [comment]
For naming, I think our preference going forward will be "container" and "object" (instead of item/device).  "Device" remains strewn throughout the documentation unfortunately, though our intent was to get away from that ophyd-ism.

So: "Container Name", "Container Class", "Object Class" (@ZLLentz correct me if I'm misremembering here; naming far from my strong suit)

**Comment by untzag** [comment]
OK, that makes sense to me. Do y'all use happi to store things other than bluesky devices?

**Comment by klauer** [comment]
Not currently, but there's a fair amount of interest - er, well, _chatter_ at best - about using happi in other spots in our facility.

**Review by ZLLentz — APPROVED** [review]
This LGTM, will be very helpful!

At LCLS we've made maybe a few too many site-specific containers, I'm interested to check what this shows for us.

It also reminds me that the container classes could use some docstrings- if we could have assumed that all containers had a helpful docstring then that would have been useful to include in the table.

**Comment by ZLLentz** [comment]
Something bizarre is up with the CI, there was a 37-minute pip install build that I just killed. I'll merge after the rest of the jobs finish.

**Comment by ZLLentz** [comment]
CI docs failure unrelated

**Pull request merged**
