### PR TITLE
CI: upgrade to latest shared standard

### PR DESCRIPTION
**Pull request by klauer**
## Description
Upgrade happi CI to latest, shared standards.

## Motivation and Context
Docs build is failing on merge, for some reason. Let's get this out of the way first.

### CODE REVIEW

**Comment by klauer** [comment]
I'm at a loss as to what's happening here. For now, I'll be manually pushing a documentation update to get around these CI problems.

**Comment by klauer** [comment]
Still nonsensible results:

```
Package python conflicts for:

happi -> entrypoints -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.9,<3.10.0a0|3.4.*|>=3.5|3.8.*|3.7.*']
python=3.6
happi -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.6|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
```

I think the recipe may need reviewing as this doesn't seem right...

**Comment by klauer** [comment]
I was hopeful more constraints would allow PyPI builds to pass, but they did not. I can remove those if reviewers take issue with it.

**Comment by ZLLentz** [comment]
I need to browse our other repos, I don't remember which one but one of them had the pypi build passing...

**Review by ZLLentz — APPROVED** [review]
Changes look clean

**Comment by ZLLentz** [comment]
https://travis-ci.com/github/pcdshub/pcdsdaq/jobs/470612258 is the one I recently put on shared travis that passes, but no obvious structural difference to me other than fewer requirements:
https://github.com/pcdshub/pcdsdaq/blob/master/requirements.txt

**Comment by klauer** [comment]
Your linked passing Travis CI output notably does not have that weird new pip-2020 dependency solver. Hmm...

**Comment by ZLLentz** [comment]
It also finishes running the full test suite within a single minute, which is pretty great compared to the rest of the travis config

**Comment by ZLLentz** [comment]
The output here is bizarre: it's like parso and jedi start having a duel and eventually it breaks the whole session

**Comment by klauer** [comment]
~Jedi duel...~

Should probably try to install this locally in a fresh environment with pip to see that we can't reproduce it. At least for our purposes, this should be good-to-go on conda.

**Pull request merged**
