### PR TITLE
ENH: add happi search widget from atef

### PR DESCRIPTION
**Pull request by klauer**
## Description
Add more user-friendly happi search widget from atef.

## Motivation and Context
We made these for atef, we may as well upstream them to happi.
We need to find a home for the ophyd device tool as well - likely not happi.

## Screenshots (if appropriate):
image
image

### CODE REVIEW

**Comment by klauer** [comment]
(Rebasing on happi master; less because I want to work on this PR and more because I want to see the effect of the line-profiler 4.1.1 release)

**Comment by klauer** [comment]
We might have some updates from atef on these widgets. Perhaps we merge and then follow up?

**Comment by tangkong** [comment]
It does look like there have been some changes.  I'm happi to merge those changes in later.  

This addition does make me wonder if it's worth the time to figure out how to separate happi[ui] from happi[core].  There's not too much to this GUI currently, but I kinda liked the pure-code-ness of happi.  

also if I have to add qt tests to happi I'm gonna cry

**Comment by klauer** [comment]
I suppose we could have `happi-qt` instead? I'm fine with that I guess, but having it get out of sync would be a bit painful

**Comment by tangkong** [comment]
I do think having the viewer in this package will be helpful.  Maybe we reconsider `happi-qt` or `happi[qt]` when we accrue more substantial ui elements.  For now I'm ok with this

**Comment by ZLLentz** [comment]
Should we merge this before or after the upcoming tag?

**Comment by klauer** [comment]
This may be ready to merge? @ZLLentz @tangkong

**Review by tangkong — APPROVED** [review]
I'm ok with merging this, with the understanding that we'll have to merge in the updated version from atef and/or create happi-qt later on.

**Comment by tangkong** [comment]
closes #221

**Pull request merged**
